# Generated by Django 4.0.5 on 2022-08-19 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=400)),
                ('s_no', models.IntegerField()),
                ('video_id', models.CharField(max_length=700)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='porn.category')),
            ],
        ),
    ]
