# Generated by Django 4.0.5 on 2022-08-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='desc',
        ),
    ]
