# Generated by Django 4.0.5 on 2022-08-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porn', '0002_remove_video_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_id',
        ),
        migrations.AddField(
            model_name='video',
            name='video_title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
